### ISSUE TITLE
Early support for EAP builds?

### ISSUE THREAD

**Issue by rcdailey** [Socolin/NSubstituteComplete#6]
I've noticed over the years, that the `NSubstituteComplete` plugin never works when I run EAP builds. I think having the plugin work in EAP builds would be beneficial.

![image](https://user-images.githubusercontent.com/1768054/201114119-b53ca173-20f6-44e6-b7dc-01510e33c915.png)

**Comment by Socolin** [comment]
Hello,

I agree but I'm really busy and I don't always have time to do this. I have multiple plugins to upgrade too so it's not a 5 minutes things.
I'll try to do this soon.

Also PR are welcome :)

**Comment by rcdailey** [comment]
I'd love to help with PRs but I'm already way too overloaded...

Thanks for the quick reply!

**Comment by Socolin** [comment]
A version should be available for the EAP

**Comment by rcdailey** [comment]
Thank you very much! I'm curious: Is there a way to use a "wildcard version" so that this plugin is compatible with future versions going forward? I assume most of the time you do this, it's just changing numbers but there aren't really any compatibility concerns. I think if this were possible, it would be less of a maintenance burden on your part.

On the other hand, I get the feeling that if this were doable, you'd have already done it!

**Comment by Socolin** [comment]
The gradle plugin used to build the plugin automatically generate a restricted range for version to only works for the targeted version.

And when we publish the plugin there is a validation by Jetbrains and I'm not sure if I edited the `plugin.xml`  to put a wildcard here it would pass the validation

Also:

In the past I encountered error because I did not rebuild after EAP and they changed a method in the .NET API, the error message was very unclear and I waste some time trying to figure out what was the problem. So when I have time I do EAP and I rebuild after the release, when I don't have much time I'm doing this when the release is out.

And since Jetbrains deprecate API sometimes, it's better to rebuild each versions and fix those when they arrive with a nice warning message, instead of getting a "Reference not found" like exception when the method/class is gone.

----

This time it was only updating the version, but I spent 2-3 hours figuring out what other dependencies I needed to upgrade for the plugins with a frontend part, in java, since the targeted java version changed and there was some pre-release version of the gradle plugin to use.

I would love if they added a bot like dependabot for this :)
